![NYC Skyline](nyc.jpg)

Welcome to New York City, one of the most-visited cities in the world. There are many Airbnb listings in New York City to meet the high demand for temporary lodging for travelers, which can be anywhere between a few nights to many months. In this project, we will take a closer look at the New York Airbnb market by combining data from multiple file types like `.csv`, `.tsv`, and `.xlsx`.

Recall that **CSV**, **TSV**, and **Excel** files are three common formats for storing data. 
Three files containing data on 2019 Airbnb listings are available to you:

**data/airbnb_price.csv**
This is a CSV file containing data on Airbnb listing prices and locations.
- **`listing_id`**: unique identifier of listing
- **`price`**: nightly listing price in USD
- **`nbhood_full`**: name of borough and neighborhood where listing is located

**data/airbnb_room_type.xlsx**
This is an Excel file containing data on Airbnb listing descriptions and room types.
- **`listing_id`**: unique identifier of listing
- **`description`**: listing description
- **`room_type`**: Airbnb has three types of rooms: shared rooms, private rooms, and entire homes/apartments

**data/airbnb_last_review.tsv**
This is a TSV file containing data on Airbnb host names and review dates.
- **`listing_id`**: unique identifier of listing
- **`host_name`**: name of listing host
- **`last_review`**: date when the listing was last reviewed

In [84]:
# Import necessary packages
import pandas as pd
import numpy as np

# Begin coding here ...
# Use as many cells as you like

In [85]:
# Import 'airbnb_price.csv' file
price_file = 'data/airbnb_price.csv'
df_price = pd.read_csv(price_file)
print(df_price.info())
print(df_price.head())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25209 entries, 0 to 25208
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   listing_id   25209 non-null  int64
 1   price        25209 non-null  object
 2   nbhood_full  25209 non-null  object
dtypes: int64(1), object(2)
memory usage: 591.0+ KB
None
   listing_id        price                nbhood_full
0        2595  225 dollars         Manhattan, Midtown
1        3831   89 dollars     Brooklyn, Clinton Hill
2        5099  200 dollars     Manhattan, Murray Hill
3        5178   79 dollars  Manhattan, Hell's Kitchen
4        5238  150 dollars       Manhattan, Chinatown

In [86]:
# Import 'airbnb_room_type.xlsx' file
room_type_file = 'data/airbnb_room_type.xlsx'
xls_room_type = pd.ExcelFile(room_type_file)
print(xls_room_type.sheet_names)
df_room_type = xls_room_type.parse('airbnb_room_type')
print(df_room_type.info())
print(df_room_type.head())

['airbnb_room_type']
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25209 entries, 0 to 25208
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   listing_id   25209 non-null  int64
 1   description  25199 non-null  object
 2   room_type    25209 non-null  object
dtypes: int64(1), object(2)
memory usage: 591.0+ KB
None
   listing_id                                description        room_type
0        2595                      Skylit Midtown Castle  Entire home/apt
1        3831            Cozy Entire Floor of Brownstone  Entire home/apt
2        5099  Large Cozy 1 BR Apartment In Midtown East  Entire home/apt
3        5178            Large Furnished Room Near B'way     private room
4        5238         Cute & Cozy Lower East Side 1 bdrm  Entire home/apt

In [87]:
# Import 'airbnb_last_review.tsv' file
review_file = 'data/airbnb_last_review.tsv'
df_review = pd.read_csv(review_file, delimiter='\t')
print(df_review.info())
print(df_review.head())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25209 entries, 0 to 25208
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   listing_id   25209 non-null  int64
 1   host_name    25201 non-null  object
 2   last_review  25209 non-null  object
dtypes: int64(1), object(2)
memory usage: 591.0+ KB
None
   listing_id    host_name   last_review
0        2595     Jennifer   May 21 2019
1        3831  LisaRoxanne  July 05 2019
2        5099        Chris  June 22 2019
3        5178     Shunichi  June 24 2019
4        5238          Ben  June 09 2019

What are the dates of the earliest and most recent reviews? Store these values as two separate variables with your preferred names.

In [88]:
# Convert 'last_review' to date
df_review['last_review'] = pd.to_datetime(df_review['last_review']).dt.date

In [89]:
# Store variables with oldest and latest reviews
oldest_review = df_review['last_review'].min()
latest_review = df_review['last_review'].max()
print(oldest_review)
print(latest_review)

2019-01-01
2019-07-09

How many of the listings are private rooms? Save this into any variable.

In [90]:
# Normalizing case differences
df_room_type['room_type'] = df_room_type['room_type'].str.lower()
# Counting room types
count_rooms = df_room_type['room_type'].value_counts()
count_private = count_rooms["private room"]
# Store variable for private rooms 
count_private

11356

What is the average listing price? Round to the nearest two decimal places and save into a variable.

In [91]:
# Remove 'dollars' and convert type to float
df_price['price'] = df_price['price'].replace('dollars','',regex=True).astype(float)
# Calculate the average price and define 2 decimal places 
average_price = df_price['price'].mean().round(2)
average_price

141.78

Combine the new variables into one DataFrame called review_dates with four columns in the following order: first_reviewed, last_reviewed, nb_private_rooms, and avg_price. The DataFrame should only contain one row of values.

In [92]:
dict = {'first_reviewed':oldest_review,'last_reviewed':latest_review,'nb_private_rooms':count_private, 'avg_price':average_price}
review_dates = pd.DataFrame([dict])
print(review_dates)

  first_reviewed last_reviewed  nb_private_rooms  avg_price
0     2019-01-01    2019-07-09             11356     141.78